instaloader.py

* Consistency wrt. `if a not in b` vs `if not a in b`
* `download_stories` is expecting `"items"` to be available since [`99620ec`](https://github.com/Thammus/instaloader/commit/82ae31cea58c7d1361a2e5e9eea8174881874b72). (Not really sure about raising vs continuing. Maybe using `self._error_catcher()` is the right thing to do, in the unlikely event of both `reels_tray` and `reel_media` returning without an `"items"`.)
* The millisecond issue doesn't rely on `fromtimestamp` raising an exception since [`9eddc03`](https://github.com/Thammus/instaloader/commit/9eddc03cf1f1c98e764db3afc28482bad858c1ea), so one call with the (possibly adjusted) `date_float` is sufficient.
And I would probably want to see something like:
```
for (count, item) in enumerate(user_stories["items"]): …
```

Minor stories-related cleanup

---

instaloader/instaloader.py

Use string formatting instead of `str(0) + str(index)` and don't assume file extension is three characters.

Refactor `get_filename`

---

instaloader/instaloader.py
instaloader/structures.py

Added likes_count to PostCommentAnswer tuple to allow for scraping of comment likes along with the comments themselves.

Added likes_count to PostCommentAnswer tuple

---

instaloader/instaloadercontext.py

Closes https://github.com/instaloader/instaloader/issues/388

handle alternate rate limit exceeded behavior of redirecting to login

---

instaloader/instaloadercontext.py
instaloader/structures.py

This seems to solve the issue #380
The issue was happening when I was logged.

Solving  KeyError: 'edge_sidecar_to_children'

---

docs/cli-options.rst
instaloader/__main__.py
instaloader/instaloader.py
instaloader/instaloadercontext.py

Adds a `request_timeout` parameter to IL instantiation.
Closes #330

support passing timeout to requests

---

instaloader/__main__.py

Shortcodes seems to be 11 or 39 chars, and hashtags probably has some length restrictions. But without definitive specifications I'd err on the side of being permissive.
Related to #571

Regex target matching

---

instaloader/structures.py

Implemented suggested feature on https://github.com/instaloader/instaloader/issues/601

[Issue #601] Add is_business_account and business_category_name 

---

instaloader/instaloadercontext.py

It should work but I don't have any Windows machine to test it.

Fixed issue #769 by using os.replace instead os.rename

---

instaloader/instaloader.py

Fixes unintended sidecar video skipping if --no-pictures is set (fixes #763).
Fixes video download if video thumbnail access fails with 410 error (fixes #773).

Fix some video download edge cases

---

instaloader/instaloader.py

Fix support for Python 3.5 prior Python 3.5.4

---

instaloader/instaloadercontext.py
instaloader/structures.py

- Fixes # https://github.com/instaloader/instaloader/blob/master/instaloader/instaloadercontext.py#L354-L355.
- What problem does the pull request solve?
- https://github.com/instaloader/instaloader/issues/778
- The changes proposed in this pull request
- regex

Fix re.search

---

docs/module/structures.rst
instaloader/__init__.py
instaloader/structures.py

- More general: What problem does the pull request solve?
Add the ability to load structures not only from files but also from python json-like objects
- The changes proposed in this pull request:
Added a method for loading structures from json-like objects and a method for receiving and further using json from structures
- Is it just a proof of concept? no
- Is the documentation updated (if appropriate)? yes, please check
- Do you consider it ready to be merged or is it a draft? ready
- Can we help you at some point? yes, please review

Add support for loading structures directly from python json objects

---

instaloader/instaloadercontext.py

since it causes IG's CDN to limit download speed
Fixes #1233 and #1145.

Do not delete referer header

---

instaloader/structures.py

@aandergr,
I've separated #1109 issue's fix from https://github.com/instaloader/instaloader/pull/1240 pull request, please have a look.

Fix for the issue with --geotags: #1109

---

docs/cli-options.rst
instaloader/__main__.py
instaloader/instaloader.py

This PR attempts to fix #854
- UnitTests are passing and the code seems to be working as intended.
- cli-options.rst is updated.

Add --sanitize-paths option

---

instaloader/instaloader.py
instaloader/instaloadercontext.py

Fixes #1414.
Please consider this WIP since I need some input about how to implement certain things, particularly about how to detect existing local file.
My idea is to:
1. detect with apparent extension (.webp) first before making the request; 
2. detect with potential *real* extension as well -- but this has to be hard-coded as ".jpg". (*not implemented yet*)
3. and then detect again once we got the correct filename (that means after we made the request, but haven't started downloading). If we already did 2, I don't know if this really is necessary, though (*not implemented yet*).
What do you think?

Using header to determine file extension

---

instaloader/structures.py

This attempts to fix https://github.com/instaloader/instaloader/issues/1471 by correcting an oversight in https://github.com/instaloader/instaloader/pull/1453.

Checks if caption is not None before normalization

---

instaloader/lateststamps.py

before writing the file
Fixes #1467 and #1494

Make latest-stamps create intermediate directories

---

instaloader/structures.py

Includes https://github.com/instaloader/instaloader/pull/1540.
This pull request adds Profile.biography_hashtags, .biography_mentions, StoryItem.caption, .caption_mentions, .caption_hashtags, and .pcaption.
It also increases code sharing between these and Post.

Add hashtags and mentions to Profile, add caption etc to StoryItem

---

instaloader/structures.py

- **A motivation for this change, e.g.**
- Fixes #1588
- **The changes proposed in this pull request**
- Add the parameter `__d` to the url to prevent the request returning the `"Sorry, something went wrong"` error.
- **The completeness of this change**
- Is it just a proof of concept? No
- Is the documentation updated (if appropriate)? N/A
- Do you consider it ready to be merged or is it a draft? Ready to merge

Fixed downloading hashtags

---

instaloader/instaloadercontext.py

- Addresses #1743 and possibly #1741, #1738 by better emulating an iOS device (iPad rather than iPhone)
Instagram accounts are being locked or banned when using Instaloader likely due to the API calls against the mobile API for iOS due to a combination of factors: 
- an outdated user-agent for version of Instagram released over 2 years ago
- unrealistic resolution for an iPhone X device that exceeds the physical limits of the device
- lack of headers that are normally provided by the iOS app
Introduction of a set of default "iPhone" (well, iPad) headers by the introducing of `default_iphone_headers` method in `instaloadercontext.py` and construction of HTTP request headers by extracting data from an existing web desktop session cookie as well as HTTP response headers from subsequent …

Update UA and enhance headers for iOS struct

---

instaloader/sectioniterator.py
instaloader/structures.py

* Closes https://github.com/instaloader/instaloader/issues/1871
* Also fixed accessing 'location' of the Post

Fixed downloading with location id

---

instaloader/structures.py

Retrieve a list of hashtags followed by a given profile since it hasn't be implemented.
Updated documentation and updated test file.

[new] Added Get Followed Hashtags.

---

instaloader/structures.py

Return an a list profiles that liked a comment.

[new] Get comment likes.

---

instaloader/lateststamps.py

Fix crash related to --latest-stamps (#2055)

---

AUTHORS.md

As mentioned in #2147 , I'm adding myself to AUTHORS.md.

Add myself to AUTHORS.md

---

docs/basic-usage.rst
docs/cli-options.rst

I simply fixed 2 small wording and grammar usages to improve documentation.

docs: fix wording and grammar usage

---

instaloader/nodeiterator.py

Fixes #2319
Possible workaround for Instagram returning empty posts list.
Seems to work, but not sure about any side effects.

Workaround for empty posts

---

instaloader/instaloadercontext.py

Updating the Instagram iOS version headers based on the latest app version.
- **Is it just a proof of concept?** No
- **Is the documentation updated (if appropriate)?** No
- **Do you consider it ready to be merged or is it a draft?** Ready
- **Can we help you at some point?** No

Update headers for iOS
