instaloader.py
I've come across several implausible values for `device_timestamp` (such as 182428140, which would be in october 1975, assuming millisecond). I guess it is due to improperly configured phones, or maybe some third party software that's mangeling the EXIF data on images before posting. Anyway. Since by the nature of stories, the `taken_at` timestamp (presumably when the instagram servers received the post) ought to be approximately when an image was actually taken. So there's no real value trying to use the timestamp provided by the photo-taking-device.
=> Ignore `device_timestamp` for stories.

instaloader/instaloader.py
50a5330fecb1272487fdd600416354c83ef8922f breaks `:stories` since userids is None (non-iterable).
Maybe `get_stories()` should also be adjusted to accept the empty list as `userids`, not only `None`, as an indication that all stories are to be retrieved.
And maybe https://github.com/instaloader/instaloader/blob/7f81985911721115566e5516bb34e7b2c80c2165/instaloader/__main__.py#L121-L126
ought to, at least, emit a warning if `stories_only`. I suppose there might be a semi-valid usecase for `--stories-only @user1 @user2 ...`. But `if stories_only and target[1:] == username` I don't see any reason to bother fetching the followees at all.
Similarly, people using `@myself --fast-update` could be steered towards `:feed`, possibly with an apropriate path pattern. Since that would accomplish what …
=> Fix :stories

docs/cli-options.rst, instaloader/__main__.py, instaloader/instaloader.py
I found that when Instaloader is interrupted (ctr-c, computer crash, etc) in the middle of a run, it may not correctly save the last picture. This is a commit mode that I scrapped up to make sure Instaloader will redownload the corrupted picture in its next run.
The commit mode ensures pictures are not corrupted when Instaloader is
unexpectedly interrupted. In the case that the last picture is corrupted
because of an interruption, Instaloader will redownload the picture
in the next run. Since the metadata is the last object saved to disk,
we can consider a post as "committed" if its json metadata file exists and
is not malformed. Instaloader should download any posts which are not
committed. Downside is commit mode requires metadata to be saved.
=> Added commit mode

docs/basic-usage.rst, docs/cli-options.rst, docs/index.rst, instaloader/__main__.py, instaloader/instaloader.py, test/instaloader_unittests.py
This adds a new query option, `%location_id`, which will make Instaloader scrape posts for a given location.
Example, for the [Plymouth Naval Memorial](https://www.instagram.com/explore/locations/362629379/plymouth-naval-memorial/) (location ID 362629379), one would query posts as follows:
`instaloader %362629379`
Apart from that, locations mostly function as hashtags, i.e. `--count` etc work.
Unfortunately, Instagram location names are not unique; the location ID is. So querying by ID is necessary to avoid ambiguity.
This is my first PR in this repository, so I'm grateful for any feedback or pointers on what else to add or document! The choice for `%` as a prefix is particularly arbitrary, so if anyone has a better idea I'm all ears.
=> Location search

instaloader/instaloader.py
```
Retrieving posts from profile xxx.
[  1/ 19] 1920293015977865613 - 2018-11-09_01-17-30.jpg exists ["real …] unchanged Traceback (most recent call last):
File "/usr/bin/instaloader", line 11, in <module>
load_entry_point('instaloader==4.2.4', 'console_scripts', 'instaloader')()
File "/usr/lib/python3.7/site-packages/instaloader/__main__.py", line 410, in main
storyitem_filter_str=args.storyitem_filter)
File "/usr/lib/python3.7/site-packages/instaloader/__main__.py", line 186, in _main
download_stories, fast_update, post_filter, storyitem_filter)
File "/usr/lib/python3.7/site-packages/instaloader/instaloader.py", line 999, in download_profiles
downloaded = self.download_post(post, target=profile_name)
File "/usr/lib/python3.7/site-packages/instaloader/instaloader.py", line 480, in …
```
=> There can be comments without any answers

instaloader/structures.py
I saw the abbreviated caption output from save_caption and realized it was perfect for `--filename-pattern`.  Even if this pull request is not accepted, please do not abandon the idea within.  The ability to put captions in file names is *very* useful.
=> New Format Specifier: {pcaption}

instaloader/instaloadercontext.py
Upon checking the POST request made by Instagram, they started encrypting the password starting with `#PWD_INSTAGRAM_BROWSER:10`, in my case. When looking at the source, I came across the following:
```js
const t = '#PWD_INSTAGRAM_BROWSER',
n = Object.freeze({
PLAINTEXT: '0',
ROTATED_ENCRYPT: '6',
FALLBACK_ENCRYPT: '9'
});
```
Apparently the new request sends it in the form of something like `<#endpoint>:<encryption_version>:<timestamp>:<aes(?)_encrypted_password>`. However, as @pgrimaud found, we can send the login request using the plaintext password as opposed to having to encrypt it.
Of course this is only a temporary solution. I think it'd be better to implement the encryption; however, this will do in the meantime.
Solves: https://github.com/instaloader/instaloader/issues/615 …
=> Workaround for Instagram's encrypted login.

instaloader/instaloader.py
…in _PostPathFormatter.
Suggested by @Thammus 
This fixes issues of path problem on Windows such as #304, #529, etc.
This also overrides #553.
Also made the following changes:
1. Changes substitution of colon to full-width colon (U+FF1A) instead of MODIFIER LETTER COLON (U+A789) to be consistent with others (we use full-width backslash, pipe, etc. already).
1. Also replaces `\r` on Windows with space, just like `\n`.
=> Only substitute characters from auto generated fields

docs/basic-usage.rst, docs/cli-options.rst, instaloader/instaloader.py
The presence of a sessionfile avoids the usage of the failure-prone login mechanism.  This commit addresses a suggestion in #615 to store the sessionfile in a persistent path rather than a path within a temporary directory if no `--sessionfile` parameter is given.
The default path is now:
- `$XDG_CONFIG_HOME/instaloader/session-USERNAME` or `~/.config/instaloader/session-USERNAME` on Unix,
- `%LOCALAPPDATA%\Instaloader\session-USERNAME` on Windows.
If no file exists in the new path, Instaloader tries loading from the path where the sessionfile was stored before this commit, hence it automatically migrates to the new sessionfile path.
=> Let --sessionfile default to a more persistent path

instaloader/__main__.py, instaloader/instaloadercontext.py, instaloader/structures.py
If logged-in, Post.url and Post.get_sidecar_nodes() now use the iPhone API endpoint to obtain the highest-resolution image version. Resolves #630.
A notice "Warning: Use --login to download higher-quality versions of pictures" is issued if the user tries to download posts without being logged-in.
Further, the message "Errors occurred:", which is displayed when the InstaloaderContext is closed, has been changed to "Errors or warnings occurred:".
Since fetching the highest-quality requires being logged in, this further closes #267.
=> Download highest-resolution images if logged-in

instaloader/instaloader.py
Use os.path.join() for joining paths rather than `+'/'+`.
os.path.join() uses `/` on Unix-ish and `\` on Windows. On Windows, this makes the following improvements:
- Visual consistency with `/` and `\` not being mixed-up in one path (`os.path.join()` has already been used in many places).
- Allow using the \\\\?\ bypass method, e.g. with
```--dirname-pattern=\\?\D:\{target}```
The \\\\?\ bypass method fails when `/` is used as path separator. With the \\\\?\ bypass method, we can create directories whose name would otherwise be considered invalid, such as directories starting with `aux.`.
Allowing the use of the \\\\?\ bypass method alleviates #185, since with a special dirname pattern parameter we can instruct Instaloader to still create the there-mentioned problematic directories.
=> Consistently use native '\' path separator on Windows

docs/basic-usage.rst
Update documentation to make it more clear on how to download single post. Also, added example. (#398)
=> add explanation on downloading single post

instaloader/__main__.py, instaloader/instaloader.py, instaloader/instaloadercontext.py
Rather than checking the json file to make sure posts have been successfully downloaded, data is stored in a temporary file which is renamed when downloading has finished, as suggested in #257.
Same changes as in #661, except `SUPPRESS` for the CLI argument.
=> Deprecate commit-mode

docs/as-module.rst, instaloader/__init__.py, instaloader/instaloader.py, instaloader/instaloadercontext.py, test/instaloader_unittests.py
Move InstaloaderContext's rate controlling logic into a class RateController with fine-grained methods to enable easily changing Instaloader's behavior regarding rate limits.
For example, this makes it possible to easily
- raise an exception instead of sleeping, as has been asked for in #641, by overriding `RateController.sleep()`,
- use a lower query rate than default, by overriding `RateController.count_per_sliding_window()`.
Also, this changes the rate for logged-in queries as it seems that higher rates are allowed now.
=> More flexible Rate Controller

instaloader/structures.py
There are two main changes made:
For users, we request /{username}/feed/ instead of /{username}/. For some
reason, this completely bypasses the login redirect. This page doesn't
work in browser while blocked, but fortunately all the data we need is
just present in the HTML page.
For posts, we change from using the /p/ page to using the graphql
endpoint for the same data, which is still subject to graphql rate
limits, but is not subject to login redirects. The data is identical
between the two pages, apart from the object keys being sorted
differently and rhx_gis being missing on graphql.
Yes, this now unblocks access from VPNs, Tor, cloud servers, etc.
\-
This is my first time contributing to Instaloader, though I'm familiar with how Instagram works, since I'm the main developer of …
=> Bypass IP-based redirects to /accounts/login

README.rst, docs/as-module.rst, docs/cli-options.rst, docs/conf.py, docs/index.rst, instaloader/__init__.py, instaloader/__main__.py, instaloader/instaloader.py, instaloader/instaloadercontext.py, instaloader/nodeiterator.py, instaloader/structures.py
With this change, Instaloader is capable of resuming a previously-aborted download loop.  To do so, it creates a JSON file within the target directory when interrupted, that contains all the necessary information to later resume that operation.
Resuming an interrupted download is supported for most, but not all targets. It is supported for:
- Regular profile posts,
- IGTV posts
- Saved posts,
- Tagged posts,
- Explore posts.
This supersedes #683 and closes #636.
I consider it ready to be merged, however open for discussion, critics, testing, etc.
=> Resume a previously-aborted post download loop

instaloader/structures.py
I noticed that a post's `owner_id` is obtained from the respective `owner_profile`. If the `owner_profile` has not been fetched yet, an additional http request is made. However, if the `Post` instance has been created from a `hashtag.get_posts()` iterator, the `owner_id` is already available, and the additional http request is unnecessary. As far as I can see, the PR avoids this unnecessary (and costly) http call.
=> Avoid additional http request to obtain `owner_id`

docs/cli-options.rst, instaloader/__main__.py, instaloader/instaloader.py, instaloader/instaloadercontext.py
Sets a default request timeout of 300 seconds to fix Instaloader hanging indefinitely when used on an unstable internet connection without using `--request-timeout`, such as in #810.
=> Enable default request timeout of 300 seconds

instaloader/instaloader.py
This updated graphql query hash returns all fields for `tappable_objects`. These fields were missing/partial when using the old query hash.
This allows to get the full json metadata of a story. Fixes #871
=> Update graphql query hash used for stories

docs/basic-usage.rst, instaloader/instaloader.py
Please describe:
- Implement feature issue #892 
- More general: What problem does the pull request solve?
The new feature would download posts and save the images/videos with the original filenames.
- The changes proposed in this pull request
The implementation follows the other options for the filename-pattern parameter. As filename is related to a single file and not the whole post, for sidecar nodes the filename is determined again.
- Remark
Using this option alone media from one post is only grouped together by the file modification timestamp.
- Is it just a proof of concept? *No*
- Is the documentation updated (if appropriate)? *Yes*
- Do you consider it ready to be merged or is it a draft? *ready*
- Can we help …
=> Save content using original filenames

docs/cli-options.rst, instaloader/__main__.py, instaloader/instaloader.py, instaloader/structures.py
As said in the title, this pull request is about a **feature implementation** of issue #739. The new change allows to **select which image** or **range of images** to download in an Instagram sidecar.
There's a new parameter, `--slide`, that by default is an empty string. If setted, it allows to:
* download just *one image* with the `index` specified
* download an interval of images, using this format: `start_index`:`end_index`, for example `1:3` (endpoints included)
The core of the new feature is almost entirely implemented inside the `download_post()` method.
The index starts from 1, where 1 is the leftmost image in the sidecar. The index numbers can't be negative. If the index/interval is invalid, for example in case you are out of range, the download of the post is *skipped*
* **Is it …
=> Implementation of feature #739

instaloader/structures.py
For the solution of issue [#969](https://github.com/instaloader/instaloader/issues/969)
-- A motivation for this change
- Fixes # 
- Some post of instagram has title as same as caption but current version of instaloader does not give title of post.
- To get title of post, I've added one property method called title as same as caption method in class Post.
-- The completeness of this change
- In json response of graphql query, it gives title of post with key name as title as same as location in value of shortcode_media 
but instaloader was not considering it.
- Added one method named _title_ in class _Post_ which will get value of title from __full_metadata_dict_  dictionary.
- If title is not present in json response, it will return None.
- Need to update documentation for this method.
- …
=> Add method to get title of post (#969)

instaloader/structures.py
- It's necessary because for the old query_hash IG isn't returning the full structure any more.
- So the old query_hash is replaced with the current one.
Urls are from [https://www.instagram.com/cats_of_instagram/](https://www.instagram.com/cats_of_instagram/).
This one is currently used in Instaloader:
[https://www.instagram.com/graphql/query/?query_hash=472f257a40c653c64c666ce877d59d2b&variables=%7B%22id%22%3A%227013409%22%2C%22first%22%3A50%2C%22after%22%3A%22QVFBNmlPTlE4YU15U0R1X1otUVNuSFVxY3M2QWVqbWlfcFBVVGNyY0NQeFR4Nkp6RVR3Vl9TV016T3UyY3kyTm1Ib2h2NGw5aDBXc3dMUmFiVWY5M0J3Vg%3D%3D%22%7D](https://www.instagram.com/graphql/query/?query_hash=472f257a40c653c64c666ce877d59d2b&variables=%7B%22id%22%3A%227013409%22%2C%22first%22%3A50%2C%22after%22%3A%22QVFBNmlPTlE4YU15U0R1X1otUVNuSFVxY3M2QWVq …
=> Update the query_hash for post downloads

instaloader/instaloader.py
- When a post contained sidecars, the filename for caption, json etc. was changed. It was no longer the original filename like before.
- If the post contains sidecars, a local variable is used to build the filenames for the sidecar media.
=> Fix issue 892 Save content using original filenames (PR 893)

docs/cli-options.rst, instaloader/__main__.py, instaloader/exceptions.py, instaloader/instaloader.py, instaloader/instaloadercontext.py, instaloader/structures.py
This makes the support for calling the iPhone media endpoint optional, using the `--no-iphone` argument.
Should fix #1035. The motivation for this change is that no matter what I did before, always got 429s.
=> Make iPhone endpoint query optional

instaloader/instaloader.py
**What problem does the pull request solve?** Since profiles are not downloaded in the order specified in the command line (and if one downloads followees, one doesn't even know which profiles will be downloaded), it's not possible to know the progress of the scraping process.
**Changes**: This changes the log lines "Retrieving stories from profile..." and "Downloading profile" to include a counter ##/## showing the current profile number and the total (if known).
**Is it just a proof of concept?** I believe it's complete
**Is the documentation updated (if appropriate)?** Doesn't apply
**Do you consider it ready to be merged or is it a draft?** I believe it's ready
**Can we help you at some point?** It's a small change, but nevertheless feel free to suggest improvements.
=> Show progress of scraping

docs/basic-usage.rst, docs/cli-options.rst, instaloader/__main__.py, instaloader/instaloader.py, instaloader/structures.py
Currently profile pics are saved with a fixed filename template, that doesn't even include the owner's name.
This changes the behaviour so that when saving profile pics, highlight covers and hashtag profile pics, the filename is created based on `--filename-template`.
Not all tokens have meaningful values: there is not `shortcode` or `mediaid`, for example. They're replaced with other values or with an empty string. But all tokens listed in the documentation are supported (and some extra ones that might be useful).
**Is it just a proof of concept?** No
**Is the documentation updated (if appropriate)?** I don't think there is anything to add to the documentation, but I'll certainly add if someone believes it needs to be updated.
**Do you consider it ready to be merged or is it a draft?** …
=> Use --filename-pattern for profile pics and covers

docs/cli-options.rst, instaloader/__main__.py
The documentation for `--count` was out of date in the changed files. It has been corrected to note that `--count` works for the four options `#hashtag`, `%location_id`, `:feed`, and `:saved` as evidenced in `_main` within `instaloader/__main__.py`
I have tested my changes and this pull request seems ready.
=> update documentation for --count option

README.rst, docs/basic-usage.rst, docs/cli-options.rst, docs/module/structures.rst, instaloader/__init__.py, instaloader/__main__.py, instaloader/instaloader.py, instaloader/lateststamps.py
See #1122 for details.
This adds an option `--latest-stamps` pointing to a file that stores the timestamp each profile was last downloaded. On the next run, only posts newer that that timestamp are downloaded.
Currently works for posts and stories. I could try to enhance it to support tagged posts, hashtags, etc. As noted on #1122, some feeds are not chronological. I suppose a solution like in #666 could be used. Storing ids of everything downloaded would probably take too much space.
Profile IDs are also stored in the stamps file, and there's also a check to avoid redownloading profile pics. In this case, since there isn't a reliable timestamp, the file name is used.
BTW, This feature was inspired by a similar functionality in https://github.com/arc298/instagram-scraper/, and the file …
=> --latest-stamps, like --fast-update, but without the need to keep downloaded files (Fixes #1122)

instaloader/structures.py
Fixes #1029.
Earlier, if someone had an email address in the caption, those were provided as mentions in the `Post.mentions` attribute. With [this update](https://regex101.com/r/X5R3E7/1/) to the regular expression, email addresses are no longer ingested.
This change is complete, and no need for updates in documentation as the attribute should work as before. **Ready to be merged.**
=> Mentions include email addresses  Fixes #1029

instaloader/instaloader.py
While this isn't really an error, it requires user action, so the message
is printed to stderr even with --quiet, and repeated at the end when that
option is not enabled.
=> Profile renames are reported even if --quiet is enabled (fixes #1159)

instaloader/structures.py
If you perform too many queries from a certain IP `has_public_story()` no longer works.
Using this simple example:
``` python
import instaloader
L = instaloader.Instaloader()
L.load_session_from_file('...')
profile = instaloader.Post.from_shortcode(L.context, 'bmw')
print(profile.has_public_story)
print(profile.has_viewable_story)
```
``` bash
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
Traceback (most recent call last):
File "e:/instaloader/TODO.py", line 9, in <module>
print(profile.has_public_story)
File "e:\instaloader\instaloader\structures.py", line 803, in has_public_story
File "e:\instaloader\instaloader\instaloadercontext.py", line 430, in graphql_query
session=tmpsession)
File …
```
=> Fix and Update has_public_story Functionality

instaloader/instaloader.py
Using itertools.takewhile() on a NodeIterator returns a plain Iterator,
and so it's not resumable.
The strategy has been altered to pass an extra argument to
posts_download_loop, a lambda that is evaluated for each post, and
causes the loop to stop when it returns false.
=> Make downloads using --latest-stamps resumable

instaloader/instaloadercontext.py
taking csrf token from the instagram login page as it is empty using the old url
this should fix JSONDecodeError when trying to log in (at least in Europe). The error was described in #1150 as well as #1191
=> fixes #1150 and #1191

instaloader/instaloader.py
Only use last_scraped when it has certainly been initialized before.
=> Avoid uninitialized variable (fixes #1203)

instaloader/instaloader.py, instaloader/nodeiterator.py, instaloader/structures.py
Fixes #1206 
The timestamp of the most recent post is cached in NodeIterator (and saved to the disk), and this timestamp is stored, instead of the timestamp instaloader was run.
This way, even in later resuming runs the timestamp stored is the same that would have been stored if the first run.
This is not exactly what has been propsed in the bug discussion, but please take a look and tell me what you think of the solution.
=> Fix interruped downloads with --latest-stamps (#1206)

instaloader/instaloadercontext.py, instaloader/structures.py
This fixes #1022.
Also, Instaloader supports to download single post which works with Stories. But the returned data is slightly different and can't be properly handled by existing `Post` class. I patched this part as well. 
They are called `typename` = `StoryImage` and `StoryVideo` (NOT `GraphStoryImage` or `GraphStoryVideo` returned from the Stories timeline as `StoryItem`.)
Weirdly, the `StoryVideo` returned by single post API doesn't behave like `GraphStoryVideo` returned by Stories timeline either. It has no `self._node['video_url']` or `self._node['video_resources']`. So you can only get the video from `self._iphone_struct['video_versions']`.
In long term, I think it's better we either create a base class `Item` which both `StoryItem` and `Post` can inherit from; or just merge the …
=> Pick best video (#1022)

instaloader/instaloader.py
This sould fix the problem identified in #1114.
=> Avoid uninitialized variable when called with :stories

instaloader/instaloader.py
If you try to use `instaloader` to retrieve highlights that are grouped by naming it `.` or `..` you'll be having a problem with your OS. Besides, files starting with dots in Linux OS will be considered hidden folders, and you'll have some trouble seeing/moving them unless you use extra commands.
This commit uses the existing folder naming sanitization function and extends its capabilities for the above-mentioned case.
Basically, it will replace folders that start with a dot (".") into another similar one ("․")․
=> Fix the issue with folder names starting with dots

instaloader/structures.py
Fixes #1320.
Also improves the workflow a little bit.
=> Fix KeyError for video_url, and better workflow

instaloader/nodeiterator.py
- **A motivation for this change, e.g.**
- Fixes #1017 #1143 #910 
- More general: 
There is currently a problem with Instagram that sporadically the comments do not come to an end and can be scraped endlessly.
The has_next_page-flag (inside the request response) is always true although the comments are repeated.
This error does not always occur, but mainly with larger profiles and the consequence is that you quickly run into an HTTP 429 Error (Too Many Requests).
The problem can also be reproduced in the browser
Test data: https://www.instagram.com/p/CVyEdhbIXPG/
- **The changes proposed in this pull request**
-  change the nodeiterator __next__ method to check if the response is the same than before
- Is it just a proof of concept? It's just a poc 
- …
=> Endless loop when receiving comments

instaloader/structures.py
- Fixes issue #1305.
- More general: from `--post-metadata-txt="{date_local:%Y-%m-%dT%H:%M:%S.%f%z}"`  %z in datetime style formatting options doesn't return offset
This is my very first time collaborating with the community, also this is one of my first projects with python, with this implementation what I do is substracting creation date in local time zone vs creation date in UTC, with that offset I can obtain the timezone info.
=> datetime style formatting options doesn't return offset

instaloader/instaloader.py
Since `Post.date_local` now already returns a timestamp with the appropriate timezone, it's not necessary to add timezone information to timestamps when comparing dates for `LatestStamps`.
=> Remove unnecessary conversion to timezone aware timestamp

instaloader/structures.py
This attempts to fix https://github.com/instaloader/instaloader/issues/1455 by restricting mentions to only being ASCII.
=> Mention regex will now be restricted to ASCII

instaloader/instaloader.py, instaloader/structures.py
This PR aims to fix the symptoms described in #1530, where error messages contradict themselves. It does _not_ fix the underlying problem (“Could not find "window._sharedData" in html response.“), though. Still, I think this is worth it, since profile loading might break in a similar fashion some time in the future.
I'm new to this codebase, so I do lack the “bigger picture”.
---
https://github.com/instaloader/instaloader/blob/385c6c8a353458b8e1f5d1eacd98a714a41e9fc0/instaloader/instaloader.py#L1326-L1337
These are the local variables of interest:
```py
profile_id == 1234
profile == None
profile_name == 'somename'
newname == 'somename'
```
And here's what happens:
- `Profile.from_username` raises `ProfileNotExistsException`
- It's caught afterwards
- `profile_id` is read from the file
- …
=> Fix incorrect error messages when certain requests fail

instaloader/structures.py
Retrieving a users profile was not possible anymore, due to internal changes of instagram. 
It seems to work fine when switching to the new 'api/v1/users/web_profile_info/?username=xy' endpoint.
Up to now I just tested that retrieving the profile info as well as posts is working with this fix, so it is still a WIP.
I'm not too familiar with the internals of instaloader so maybe someone with more knowledge can help out to verify if everything works fine again...
When final this should fix #1553 as well as #1560
=> fixed fetching a users profile information

instaloader/structures.py
A further fix about issue mentioned in #1238.
After @aandergr 's commit https://github.com/instaloader/instaloader/commit/c0e5d0475bff1507c930d4ceefb5d66686caee5d, a single story can be properly handled; however, the original issue still somewhat exists: higher quality image from iPhone API won't be fetched if a single Story is feeded in and then `.download_storyitem` is called, due to its type being "StoryImage" instead of "GraphStoryImage". 
This fixes it.
Thanks!
=> Handle StoryImage in StoryItem.url

docs/cli-options.rst
Just a minor addition to the docs, stating explicitly that you can import more than one argument file.
=> Make docs explicit about importing multiple argument files

instaloader/instaloader.py, instaloader/instaloadercontext.py
This PR adds `Instaloader.save_session` and `Instaloader.load_session`. The session object can now be imported/exported as a regular Python `dict`. 
This can be really useful when, for example, you are working in a serverless environment and want to easily store/retrieve the session for reuse from a database (like *DynamoDB*) without relying on expensive file system I/O operations.
- **Is it just a proof of concept?**: No, it's production ready
- **Is the documentation updated (if appropriate)?**: Yes
- **Do you consider it ready to be merged or is it a draft?**: Ready to merge and ship on the next release
- **Can we help you at some point?**: Nothing much to do anymore, but everything can be improved 😄
=> Add save and load session from dict

docs/module/nodeiterator.rst, instaloader/instaloader.py, instaloader/instaloadercontext.py, instaloader/nodeiterator.py, instaloader/structures.py, test/instaloader_unittests.py
This PR changes type hints to use the PEP 526 typing syntax and replaces untyped `collections.namedtuple`s with `typing.NamedTuple`s.
=> Improve typing syntax and type NamedTuples

instaloader/instaloader.py, instaloader/nodeiterator.py, instaloader/structures.py
IG now allows posts to be pinned, and they are return first by `Profile.get_posts()`. This makes `--fast-update` and `--latest-stamp` stop too early (as the first post is considered already downloaded) and posts newer than the pinned post are not downloaded. See #1582 and #1584.
- **The completeness of this change**: It's complete, hopefully
- **Is it just a proof of concept?**: No
- **Is the documentation updated (if appropriate)?** I think no changes are necessary
- **Do you consider it ready to be merged or is it a draft?**: Implementation is complete, but further tests would be useful
- **Can we help you at some point?** Yes
The ideal solution would be to return pinned posts in their proper chronological order. This would require storing pinned posts in a "pending" list and add some …
=> Handle pinned posts with --fast-update and --latest-stamps

instaloader/instaloader.py
- Fixes #1623 .
Write caption in text mode instead of binary mode, so the system newline separator (`\r\n` on Windows, for example) would be used instead of fixed `\n`. It shouldn't affect our duplication check on old caption file(s), since they're always compared with `\r\n` replaced with `\n`.
=> Write caption in text mode. Fix #1623

instaloader/instaloader.py, instaloader/structures.py
Reduce iPhone API calls. Helps issues like #1676, #1658, etc.
Don't try to use the iPhone API when merely comparing the profile pic URL with the local stamp.
This saves us some API calls when using `--latest-stamps`.
From what I can see, if you are updating lots of profiles, and most of them have no new posts (so no time wasted on checking posts), it would call this API for checking each profile pic way too fast and will got your account suspended (especially if you're using `--no-sleep`). This isn't needed because all the variant, including the web one, has the same remote URL (sans the query parameters). We only need to fetch from iPhone API when the avatar is actually changed. 
Completed, ready to merge.
=> Don't use iPhone api when merely comparing profile_pic URL with existing one

instaloader/structures.py
- Fixes #1633 for stories.
- The changes proposed in this pull request
- Use `api/v1/feed/reels_media` endpoint to download story iphone struct instead of the old `api/v1/media/`, which doesn't work with reshared stories.
- Now also download entire iphone structs for all the stories in a Highlight first, instead of fetching them one by one.
- Is it just a proof of concept? No
- Is the documentation updated (if appropriate)? No need
- Do you consider it ready to be merged or is it a draft? Ready to merge
Using a different api endpoint for stories. It works for a batch I tested so far, re-shared or not.
I haven't got any example of "re-shared posts" from the original issue, so I can't really test them. The change …
=> Use api/v1/feed/reels_media endpoint to get story info

instaloader/nodeiterator.py, instaloader/structures.py
**Motivation**: Fixes #1701.
Not only this fixes the problem, but it makes the code simpler. However, the type of the `is_first` callback has been changed. But sine this is a new feature (and very specific), I don't think this change will be a problem.
**Is it just a proof of concept?** No
**Is the documentation updated (if appropriate)?** Not necessary
**Do you consider it ready to be merged or is it a draft?** Ready
**Can we help you at some point?** This is a simple change and should be complete, but I'm open to suggestions
=> Fixes incorrect latest stamp when download is resumed (#1701)

instaloader/instaloadercontext.py
In some cases (possibly when requests are made to `i.instagram.com`), the redirect to login uses host `i.instagram.com` instead of `api.instagram.com`:
```
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=profile to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
```
This is not detected by instaload as a login request, and the application seems to enter a redirect loop, which results in getting 429 responses.
This change just adds the new URL to the detection of login required, letting the existing logic take over.
**Is it just a proof of concept?**: No
**Is the documentation updated (if appropriate)?** Not necessary
**Do you consider it ready to be merged or is it a draft?** Ready
=> Detect redirects to https://i.instagram.com/accounts/login, fixes redirect loop

instaloader/instaloadercontext.py
Updating the Instagram iOS version headers as the version currently being used is no longer supported and prevents login (most likely also being used to flag accounts).
- **Is it just a proof of concept?** No
- **Is the documentation updated (if appropriate)?** No
- **Do you consider it ready to be merged or is it a draft?** Ready
- **Can we help you at some point?** No
=> Update iOS version headers

instaloader/instaloadercontext.py
This is a small change that adds the contents of the response to the log message when the download is aborted with one of the error codes specified with the command-line option `--abort-on`.
I find the contents to be useful, sometimes it just says "You've been logged out", sometimes something like "Challenge required". And it would help in the case of other errors as well.
**Is it just a proof of concept?** No
**Is the documentation updated (if appropriate)?** Not necessary
**Do you consider it ready to be merged or is it a draft?** It's ready
**Can we help you at some point?** Not necessary
=> Log the response when an abort status is received

instaloader/instaloadercontext.py
Due to changes by Instagram, the JSON previously found in `window.sharedData` is now a string located deep in some nested JSON tags. This change caused `instaloader.get_json` to throw an error in some circumstances.
Instagram also changed the contents of the JSON, making the `entry_data` key empty. This causes `instaloader.get_json` to throw another error.
The first error occurs when trying to log in, making logging in with a username and password impossible. (Logging in with a session file still works).
This PR fixes both errors by updating `get_json` to get the JSON from its new location, and removing the logic checking the `entry_data` key, which I believe is unnecessary. It fixes issues #1737, #2044, #2059, #2062, #2069, #2084, and #2086 (all related to login).
=> Fixed error when trying to log in due to changes by Instagram

instaloader/instaloadercontext.py
Instagram made some changes on their end that resulted in an error when logging in.
```
Fatal error: Login error: JSON decode fail, 403 - Forbidden.
```
This is caused by instaloader using the wrong endpoint (`/accounts/login/ajax/` instead of `/api/v1/web/accounts/login/ajax/`). Additionally, the way instaloader gets the CSRF token (from the JSON returned by `/accounts/login/`) no longer works and throws another error.
```
Fatal error: Login error: "fail" status, message "CSRF token missing or incorrect".
```
This PR fixes both errors and makes login work again. It also removes the `is_html_query` part of `instaloadercontext.get_json`, which was only used for login and is no longer necessary.
Fixes #2126.
=> Fix 403 during login due to incorrect login endpoint and CSRF token location

docs/cli-options.rst, instaloader/__main__.py
Related issue: https://github.com/instaloader/instaloader/issues/1801
This fix avoid the simultaneous use of `--login` and `--load-cookies`.
This is necessary to avoid the conflict between username passed by the user and the logged in user account in a browser.
Testing instaloader with `--login` and `--load-cookies`
Expected result is to throw an error that says these two option cannot be used together.
Command Ran:
```console
python instaloader.py --login=its_juned42 --load-cookies=firefox
```
Observed output:
```
--load-cookies and --login cannot be used together.
```
Loading cookies by specifying a `--cookiefile`
This also works as expected.
Command Ran:
```console
python instaloader.py --load-cookies=firefox --cookiefile=C:\Users\juned_5f6qngh\AppData\Roaming\Mozilla\Firefox\Profiles\e …
```
=> Implemented fix to avoid simuntaneous use of --login and --load-cookies

instaloader/instaloader.py, instaloader/structures.py
Fixes #2142.
The property that indicated whether a post is pinned is not available anymore. As a workaround, the first five posts are treated differently (as pinned posts were): if they were already downloaded, they are skipped, but they do not cause the iteration to stop.
*  - Is it just a proof of concept?* No
*  - Is the documentation updated (if appropriate)?* Yes
*  - Do you consider it ready to be merged or is it a draft?* Ready
*  - Can we help you at some point?* I'm open to suggestion for improvement
=> Change pinned post detection, fixes #2142

docs/basic-usage.rst, docs/module/exceptions.rst, instaloader/__main__.py, instaloader/exceptions.py, instaloader/instaloader.py, instaloader/instaloadercontext.py
Fixes #2220 
Here's the general idea of how each situation is handled:
* Non fatal error (1): Before exiting, it is checked if something was logged to be repeated at the end (those are the real warning/erros that require attention). If so, the exit code is 1.
* Initialization failure (2): returned by argparse for invalid options and other parsing errors; other errors that instaloader itself detects raise `InvalidArgumentException`, which is caught at `main()`.
- `InvalidArgumentException` is also used for other errors, that generally can only be triggered when used as a module. I don't think that's a problem, but another exception could be used specifically for those initialization errors.
* Login failure (3): raises the new `LoginException`. Some more specific login exceptions were made …
=> Use different exit codes for different failures

docs/cli-options.rst, instaloader/__main__.py, instaloader/structures.py
Title: Add login required message when retrieving comments
Fixes #2230  #2234 
This change addresses the issue where Instagram now requires login to access comments on posts. By adding a message indicating the need for login, users will be informed about the requirement and can take appropriate action.
The proposed change adds a conditional check to `get_comments` method in the code. If the user is not logged in, it raises a `LoginRequiredException` with a message indicating the necessity of logging in to access comments.
=> add login required message when getting comments

.github/workflows/windows_exe.yml
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This PR fixes the deprecation warning by following the migration guide from the link above.
=> Replace deprecated 'set-output' command

docs/cli-options.rst, instaloader/__main__.py
Fixes #2241.
Also adds other browsers that the library supports but were not included in instaloader.
I don't have Vivaldi or those browsers so I haven't actually tested that the cookies are loaded, but this would be a test more of the library than instaloader itself, since all the work is done by the library.
- Is it just a proof of concept? No
- Is the documentation updated (if appropriate)? Yes
- Do you consider it ready to be merged or is it a draft? Should be ready
- Can we help you at some point?  It's a simple change and should be ready, but I'm open to any comments
=> Add support for more browsers

docs/basic-usage.rst, docs/cli-options.rst, docs/troubleshooting.rst, instaloader/__main__.py, instaloader/instaloader.py, instaloader/instaloadercontext.py, instaloader/structures.py
Fixes #2259.
Stories could only be downloaded if `--login` was used. I changed this to either `--login` or `--load-cookies`, which also logs the user in.
Otherwise the user needed to run Instaloader first just to import the cookies, and a second time (using the saved session) to actually download stories.
I've also changed error messages and the documentation in several places to refer to the process of logging in rather than to `--login` directly, but if you think that is too confusing, feel free to discard that commit.
- Is it just a proof of concept? No
- Is the documentation updated (if appropriate)? Yes
- Do you consider it ready to be merged or is it a draft? Ready
- Can we help you at some point? There's nothing I need help for, but I'm open to suggestions.
=> Download stories when --load-cookies is used

.github/workflows/documentation.yml, .github/workflows/lint.yml, .github/workflows/packages.yml, .github/workflows/windows_exe.yml
Fix GitHub Actions Node.js deprecation warnings
`The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v2.`
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, actions/setup-python@v2.`
This PR bumps actions/checkout to v4, and actions/setup-python to v5.
=> Update actions versions

instaloader/instaloadercontext.py
The first query after loading a session from cookies (done by `test_login()`) failed, and it was not caught, resulting in this stack trace:
```
Traceback (most recent call last):
File "/home/ekalin/instagrams/instaloader/instaloader.py", line 6, in <module>
main()
File "/home/ekalin/instagrams/instaloader/instaloader/__main__.py", line 559, in main
exit_code = _main(loader,
^^^^^^^^^^^^^
File "/home/ekalin/instagrams/instaloader/instaloader/__main__.py", line 163, in _main
import_session(browser.lower(), instaloader, cookiefile)
File "/home/ekalin/instagrams/instaloader/instaloader/__main__.py", line 123, in import_session
username = instaloader.test_login()
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ekalin/instagrams/instaloader/instaloader/instaloader.py", line 641, in test_login
return …
```
=> Detect errors when checking if the user is logged in

instaloader/instaloader.py
Implement check for post.mediacount before checking if posts have been downloaded which caused crashes when attempting to download posts within sidecars.
=> Fix for issue #1085

instaloader/instaloader.py
👋 Hi! I made this PR to make it possible to control the quantity of posts downloaded by profile.
The core method `self.posts_download_loop()` already has this functionality, but the external calling function `instaloader.download_profiles()` were not adjusted to receive or pass this argument further.
- Fixes #2269. (I believe this change will solve this issue) 
* Added parameter `max_count` to `download_profiles()` method
- Is it just a proof of concept? **No**
- Is the documentation updated (if appropriate)? **Yes**
- Do you consider it ready to be merged or is it a draft? **Ready** 
- Can we help you at some point? **Feel free to give me some guidelines to better solve this problem, I am fully available to do so.**
=> feat: adding max_count parameter to limit posts on download

.pylintrc, instaloader/__init__.py
PEP 561 compliance enhancement for issue #2313
By the PEP 484 and PEP 561 some of the modules api's aren't exported, so this pull request fixes it, at least partially.
Changed only `__init__.py` file with this pattern
`from .X import A` -> `from .X import A as A`
`from .X import (A, B)` -> `from .X import (A as A, B as B)`
Addition of redundant `as` operator by the [PEP 484](https://peps.python.org/pep-0484/#stub-files) marks elements as exported.
I don't know if these are all the changes needed. This is the only thing that was tearing my work apart.
I think it's ready to merge.
=> PEP 561 compliance enhancement for issue #2313

docs/basic-usage.rst
(almost) nobody says "Id est". Even I, being a native English speaker, had to search for it. It should've been "i.e." in the first place. But, even that is not needed. Let's keep it simple.
=> minor doc update in basic-usage.rst

docs/basic-usage.rst
I found the documentation for downloading single posts confusing (and I’m not the only one, e.g. #471).
When I read the example command, I thought that the leading hyphen in `-B_K4CykAOtf` was part of the shortcode – I was trying to download an Instagram post with a hyphen in the shortcode, and [some posts](https://www.instagram.com/p/-9WYAqqvSV/) have a shortcode that starts with a hyphen!
Having the URL there for a point of comparison should make this clearer.
=> Clarify that post short codes should be preceded by a hyphen

instaloader/instaloadercontext.py, instaloader/structures.py
Fixes #2338, and removes useless code.
The query used to obtain the `rhx_gis` parameter (`root_rhx_gis` function) does not work anymore.
The parameter was only used when obtaining a profile by its id, when not logged in. This query is working fine without the special header, so the whole functionality concerning rhx_gis was removed.
This also fixes this misleading messages logged when trying to obtain a profile anonymously:
```
JSON Query to : Expecting value: line 1 column 1 (char 0)
```
Note that this has changed the signature of the `graphql_query` function. I'm not sure if it's part of the public API, but it's very low level, so I changed it anyway.
- **Is it just a proof of concept?** No
- **Is the documentation updated (if appropriate)?** Yes
- **Do you consider it ready to be …
=> Remove rhx_gis header support

README.rst, docs/basic-usage.rst, docs/cli-options.rst, docs/index.rst, instaloader/__main__.py, instaloader/instaloader.py, instaloader/lateststamps.py, instaloader/structures.py
Fixes #812.
Uses doc_id-based graphql queries identified from the IG web client. Requires fetching additional metadata for each reel which can eventually exhaust IG rate limits.
=> feat: add --reels flag for downloading Reels videos from profiles

.github/workflows/windows_exe.yml
https://github.com/actions/create-release and https://github.com/actions/upload-release-asset are no longer maintained. It is suggested in the README switching to a maintained actions like https://github.com/softprops/action-gh-release. 
This PR resolves deprecation warnings like
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/create-release@v1
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/create-release@v1
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.
```
=> Update windows_exe.yml to address deprecation warnings

.github/workflows/documentation.yml, .github/workflows/lint.yml, deploy/windows/create_exe.py, setup.py
Python 3.8 is EOL. This PR removes it from lint.yml and add in 3.13.
Bumping pipenv to the latest version to support 3.13.
=> Bump pipenv, remove Python 3.8, add Python 3.13

.github/workflows/packages.yml
direct invocation of `setup.py` is considered deprecated these days; and it is desirable to publish wheels as well as sdists.
=> publish wheels

instaloader/instaloader.py
- Fixes #2536 
- Fixes #2441
- _More general:_ Reels have a separate tab on user's profile, and can have independently pinned videos (up to 3). Instaloader did not account for that
- _The changes proposed in this pull request:_ Add `possibly_pinned` to download reels loop
- _Is it just a proof of concept?_ - No
- _Is the documentation updated (if appropriate)?_ - N/A
- _Do you consider it ready to be merged or is it a draft?_ - Ready to be merged
- _Can we help you at some point?_ - Thanks to @ekalin for the tip: https://github.com/instaloader/instaloader/issues/2536#issuecomment-2755529852
=> Add `possibly_pinned` to download reels loop
